"""Add text_set models for problem management

Revision ID: 0340c345d9bc
Revises: c551f5848565
Create Date: 2025-03-25 11:03:03.456542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0340c345d9bc'
down_revision = 'c551f5848565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['problem_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_set_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('delivered_by', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['delivered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['text_set_id'], ['text_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('basic_knowledge_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_set_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_in_text', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'text_sets', ['text_set_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_knowledge_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_in_text')
        batch_op.drop_column('text_set_id')

    op.drop_table('text_deliveries')
    op.drop_table('text_sets')
    # ### end Alembic commands ###
