"""add text set models

Revision ID: 1fcac5b12033
Revises: 2252038bf4ac
Create Date: 2025-03-26 09:26:07.812987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcac5b12033'
down_revision = '2252038bf4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_set_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('delivered_by', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['delivered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['text_set_id'], ['text_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_proficiency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('text_set_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['text_set_id'], ['text_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'text_set_id')
    )
    with op.batch_alter_table('basic_knowledge_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_set_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_in_text', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'text_sets', ['text_set_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_knowledge_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_in_text')
        batch_op.drop_column('text_set_id')

    op.drop_table('text_proficiency_records')
    op.drop_table('text_deliveries')
    # ### end Alembic commands ###
