"""Add email verification and password reset fields

Revision ID: 6f80ac200402
Revises: fca5ede8dd9f
Create Date: 2025-04-27 23:14:07.596882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f80ac200402'
down_revision = 'fca5ede8dd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('classes', schema=None) as batch_op:
     #   batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('token_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_created_at')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('token_created_at')
        batch_op.drop_column('email_token')
        batch_op.drop_column('email_confirmed')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
